### ISSUE TITLE
Does not work when applied to a scrollview.

### ISSUE THREAD

**Issue by adammeaney** [dimonovdd/ImageFromXamarinUI#2]
If you try to take a "ScreenShot" of a ScrollView, this cuts off with only the visible area of the ScrollView.

I would expect similar things to happen to any control which happens to go offscreen, but I went back to my implementation before I tested anymore.

**Comment by dimonovdd** [comment]
@adammeaney Hello.  This method works as it should. And the method should not change any properties of an elements and their size. 

If you have any suggestions for expanding functionality or adding new methods, write about it or create a PR

**Comment by adammeaney** [comment]
> @adammeaney Hello. `CaptureImageAsync` method works as it should. And the method should not change any properties of an elements and their size.

I guess if "works as it should" means "behaves in a way that wouldn't be what anyone using it would desire", than yes that is true. 

I would say that if you polled 10 devs about what capture image of a view should do, it would be "Capture the entire view" not "Capture the visible part of the view". 

That is the functionality I would expect. If you need me to phrase it a specific way for you to consider it as an enhancement request let me know.

**Comment by dimonovdd** [comment]
to capture all a scrollview we need to increase its height. This will change its current height on the screen. 
 
For such purposes as you describe I'm thinking of creating a method that draws an image from elements that are not on the screen.

**Comment by adammeaney** [comment]
I have the code for doing that in the native side on a work machine I can grab to suggest to you here next week. 

It's rough right now as I didn't need a very fancy version for my usage, but I am sure it could help get the right idea. 

I didn't have to change the view size if I recall correctly.

**Comment by dimonovdd** [comment]
Can your code capture a ScrollView that is on the screen?

**Comment by adammeaney** [comment]
I used my code to capture a scrollview that was about twice the size of the screen. It's not thoroughly tested, but looks a lot like your code with a few tweaks. 

I would expect it to work on short scrollview as well, just never tested it there.

**Comment by adammeaney** [comment]
Here are my quick and dirty code segments that got me the entirety of a scrollview in bytes.

iOS:
```
public byte[] Capture(View view)
{
    var renderer = Platform.GetRenderer(view);
    var nativeView = renderer.NativeView;
    if (nativeView is UIScrollView scrollView)
    {
        var fullSize = scrollView.ContentSize;
        var currentFrame = scrollView.Frame;
        var currentOffset = scrollView.ContentOffset;

        UIGraphics.BeginImageContext(fullSize);

        scrollView.ContentOffset = CGPoint.Empty;
        scrollView.Frame = new CGRect(0, 0, fullSize.Width, fullSize.Height);

        scrollView.Layer.RenderInContext(UIGraphics.GetCurrentContext());
        var image = UIGraphics.GetImageFromCurrentImageContext();
        UIGraphics.EndImageContext();

        scrollView.ContentOffset = currentOffset;
        scrollView.Frame = currentFrame;
        return image.AsPNG()
                           .ToArray();
    }
    else
    {
        var image = nativeView.Capture();
        return image.AsPNG()
                    .ToArray();
    }
}
```

Android:
```
public byte[] Capture(View view)
{
    var renderer = Platform.GetRenderer(view);
    var nativeView = renderer?.View;
    if (nativeView == null) return null;
    var theme = Application.Current.UserAppTheme;
    if (theme == OSAppTheme.Unspecified) theme = Application.Current.RequestedTheme;
    if (theme == OSAppTheme.Unspecified) theme = OSAppTheme.Dark;
    try
    {
        Bitmap bitmap;
        if (nativeView is AndroidX.Core.Widget.NestedScrollView scrollView)
        {
            var firstChild = scrollView.GetChildAt(0);
            bitmap = Bitmap.CreateBitmap(firstChild.Width, firstChild.Height, Bitmap.Config.Argb8888);
        }
        else
        {
            bitmap = Bitmap.CreateBitmap((int)view.Width, (int)view.Height, Bitmap.Config.Argb8888);
        }
        Canvas canvas = new Canvas(bitmap);
        canvas.DrawColor(theme == OSAppTheme.Dark ? Android.Graphics.Color.Black : Android.Graphics.Color.White);
        nativeView.Draw(canvas);

        var stream = new MemoryStream();
        bitmap.Compress(Bitmap.CompressFormat.Png, 100, stream);
        var array = stream.ToArray();
        bitmap.Recycle();
        stream.Dispose();
        return array;
    }
    catch (Exception e)
    {
        return null;
    }
}
```

This is not the most polished code I have ever written, and I planned to clean up when I had time. Figured I would show what I had so far at least.

**Comment by dimonovdd** [comment]
@adammeaney
Thanks, I'll watch it tomorrow.

**Comment by dimonovdd** [comment]
As I said, the code works as I expected.
In your code, you get the root element of `ScrollView` using the tools of each platform.
We can do the same in Xamarin.Forms. And we still have the opportunity to get two different images of a `ScrollView` and `ScrollView.Content`.

 May have misunderstood you. Write to me if I can help

```xml
<Grid RowDefinitions="300" RowSpacing="0" Margin="0" Padding="0">
    <ScrollView x:Name="scroll"  Margin="0" Padding="0">
        <StackLayout x:Name="stack" Margin="0" Padding="0" Spacing="0">
            <BoxView HeightRequest="200" Background="Violet"/>
            <BoxView HeightRequest="200" Background="Green"/>
            <BoxView HeightRequest="200" Background="Blue"/>
        </StackLayout>
    </ScrollView>
</Grid>
```

|______________| **scroll** | **stack** |______________|
|:----------------:|:----------------:|:------------------:|:----------------:|
||![telegram-cloud-photo-size-2-5281011604873392586-y](https://user-images.githubusercontent.com/59065470/107884945-98dd6600-6f08-11eb-820b-d3aa91c5ef30.jpg)|![telegram-cloud-photo-size-2-5281011604873392587-y](https://user-images.githubusercontent.com/59065470/107884961-a7c41880-6f08-11eb-9dee-b076aa46576a.jpg)|

**Comment by dimonovdd** [comment]
@adammeaney 
Are you satisfied with my answer? Can I close this issue?

**Comment by adammeaney** [comment]
Huh, it somehow never occurred to me that just taking a screenshot of the View inside the ScrollView would work right.

Looks fine to me.

**Comment by dimonovdd** [comment]
@adammeaney 
thank you for your feedback
